// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwhwgsogpgextmiyhdml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3aHdnc29ncGdleHRtaXloZG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzM4MDcsImV4cCI6MjA2NTY0OTgwN30.juNs88caUkzHxmjkDC3fvex6jTVDaPy5jY0i7eYJsb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);